APPLICATION = wot_cert_exchange_cl

RIOTBASE ?= $(CURDIR)/../../../..

USEMODULE += doriot_wot_cl
#EXTERNAL_MODULE_DIRS += doriot_wot
EXTERNAL_MODULE_DIRS += $(CURDIR)/../../doriot_wot

include $(RIOTBASE)/Makefile.include
