APPLICATION = blob_test_app

USEMODULE += fmt

BLOBS += blobtest.txt blob_subdir/blobtest_subdir.txt
DIRS += blob_module
USEMODULE += blob_module

RIOTBASE ?= $(CURDIR)/../..


include $(RIOTBASE)/Makefile.include
