ifneq (,$(filter doriot_wot_rd,$(USEMODULE)))

	USEMODULE += netdev_default
	USEMODULE += auto_init_gnrc_netif

	USEMODULE += gnrc_ipv6_default
	USEMODULE += gcoap

	USEMODULE += gnrc_icmpv6_echo

	USEMODULE += od
	USEMODULE += fmt
	USEMODULE += netutils	

	USEPKG += tinycbor
	USEMODULE += tinycbor_float	

	USEMODULE += shell
	USEMODULE += shell_commands
	USEMODULE += ps
	
	USEMODULE += hashes
	USEMODULE += crypto_aes_256
	USEPKG += micro-ecc
endif

